### PR TITLE
Fix GitHub URL 

### PR DESCRIPTION
**Pull request by ciaranRoche**
Fix GitHub Url in `global.json` for [fh-api-mapper](https://github.com/feedhenry-templates/fh-api-mapper.git)

### CODE REVIEW

**Comment by ciaranRoche** [comment]
@damienomurchu @davidffrench mind having a look when you get a chance.

**Comment by grdryn** [comment]
@davidffrench @damienomurchu the build here didn't get triggered because @ciaranRoche wasn't an org collaborator. In these cases you need to go to Jenkins and approve the build to continue.

@ciaranRoche I guess you'll need to rebase this, it says it's out-of-date.

**Comment by ciaranRoche** [comment]
@grdryn awesome will get on that now, thanks.

**Comment by grdryn** [comment]
Since this is up-to-date, has 2 approvals, and the job passes, I'll merge it now.

**Comment by grdryn** [comment]
@ciaranRoche @davidffrench I'll leave it to you to decide whether or not this needs to be cherry picked to the FH-v4.6 branch also.

**Comment by davidffrench** [comment]
@ciaranRoche yes, this should be cherry-picked to the FH-v4.6 branch

**Pull request merged**
