### PR TITLE
Add in development proxy template

### PR DESCRIPTION
**Pull request by evanshortiss**
I had run this by @johnfriz and @conoro previously, but only got to do this PR now. They might want to review due to the sensitive nature of this template.

### CODE REVIEW

**Comment by conoro** [comment]
@evanshortiss I'm ok with this, since it really helps with local development. But needs to have @abstractj review it when he has time. @johnfriz You still in favour of releasing?

**Comment by evanshortiss** [comment]
@conoro yeah, big time so long as it's HTTP/HTTPS stuff. 

Security for requests is API Key and GUID for now. The service will also only proxy requests to specific hosts in the PROXY_VALID_HOSTS env var to prevent access to live hosts for example.

**Comment by johnfriz** [comment]
I'm OK with it, but agree that @abstractj needs to review this.

**Comment by abstractj** [comment]
@evanshortiss Hi Evan, I would be more than happy to look at this. Before say anything I would know how to test your changes. I just need to follow the instructions here? https://github.com/feedhenry-staff/fh-dev-proxy/blob/master/README.md

Just reading the sources I see that this change add authorization to specific hosts (keep in mind that I can be wrong). But how you prevent DNS spoofing? I thinking about the following situation:

- I add to the list abstractj.org
- Eve figure out that this host is in the authorized list
- Eve manage to turn her machine in abstractj.org and start to send requests to the app

**Comment by evanshortiss** [comment]
Hi @abstractj,

That's correct, you add abstractj.org to the list of authorised hosts to an env var for the service that's running on the platform. Your local machine will create a https request and send it to the proxy service with the details required e.g "send a request to abstractj.org/users/123", the service will then perform the request to abstractj.org host if that host is contained in the PROXY_VALID_HOSTS env var. The proxy will use DNS to resolve the host.

**Comment by evanshortiss** [comment]
I think in your example you mean Eve would _receive_ requests meant for abstracj.org, right? This scenario could happen without the proxy though so maybe I'm missing something?

**Comment by grdryn** [comment]
Hi! Closing this PR as it seems stale. If it's still relevant, please rebase and feel free to re-open. Thanks!

**Pull request closed without merging**
