### PR TITLE
Added a templates for the WFM demo

### PR DESCRIPTION
**Pull request by bleathem**
This PR introduces project and connector templates for the WFM demo.  This PR should be included for the 3.10 release.

### CODE REVIEW

**Comment by bleathem** [comment]
@corinnekrych I didn't bump the version as you suggested in IRC, since it looks like the version has already been bumped for the 3.10 release.

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* There should be an associated fhcap PR with this change - please provide a link to this
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

In order to update fhcap with your component change please execute:
`fhcap component update fh-template-apps 3.10.0 325`

**Comment by jasonmadigan** [comment]
Thanks for the PR @bleathem - is this deployed to a cluster somewhere? Also, is there an fhcap PR too (to bump the version of fh-template-apps)?

**Comment by bleathem** [comment]
I've created an fhcap PR: https://github.com/fheng/fhcap/pull/1726
I'll work on setting up a cluster running this change.

**Comment by bleathem** [comment]
@jasonmadigan this is deployed to a cluster here: http://testing.wfm.skunkhenry.com/

I realize I need to update the screenshots.  I'll update this PR shortly.

**Comment by jasonmadigan** [comment]
@bleathem took a quick look:

* Templates appeared correctly (minus the screenshots - but you're taking a look at this) for both Services and Projects
* Was able to create a Project & Service from these templates successfully

**Comment by sebastienblanc** [comment]
i'ts not working for me, the project creation fails but then the project is visible but I can not start the cloud project.

**Comment by bleathem** [comment]
I've added the WFM screenshots to the fh-template-apps repo, but the build won't suceeed without the images being present; and the images won't be present until the PR is merged.  The rh-template-apps repo really is the best place to hold the images, so I'm reluctant to move them elsewhere just to get the build to pass.

@jasonmadigan any recommendation on how to get past this chicken/egg problem?

**Comment by bleathem** [comment]
After an afternoon's fever-sleep I realize of course I can just push a commit with these images into the repo and resolve my problem. :-P

**Comment by jasonmadigan** [comment]
@bleathem sorry, just seeing this now. No worries, yes this'd be the handiest way to fix this :)

**Comment by bleathem** [comment]
I've updated the screenshots.  With the above linked fhcap cluster I've confirmed I can:

1. Create the project form the template (I have to ignore the failure message, I think caused by an npm timeout)
2. Create the WFM auth MBaaS Service
3. Create an Auth policy using the service
4. Associate the auth service with the project
5. Expose the service guid as the WFM_AUTH_GUID env var in the cloud app
6. Create a new blank forms theme for the project (appforms won't initialize if I don't)
7. Re-deploy any deployments that failed (auth service, cloud app, portal app)

I can then successfully log in to both the portal and mobile apps using the credentials trever/123.

The above instructions for consuming the WFM project template will be included as part of the WFM getting started docs.

**Comment by jasonmadigan** [comment]
@bleathem bit caught up on some on-prem stuff for the evening, but I can review this and merge first-thing Monday if that suits? Otherwise, feel ping anyone for a review.

**Comment by bleathem** [comment]
@jasonmadigan Monday is fine.
@sebastienblanc Please try the above recipe and verify it works.

**Comment by bleathem** [comment]
@jasonmadigan @sebastienblanc It would be great to merge this PR in time for the upcoming 3.10 RC release.

**Comment by jasonmadigan** [comment]
@bleathem lets do this.

**Comment by jasonmadigan** [comment]
@bleathem you might submit an fhcap PR too to bump the version of fh-template-apps to http://bob.feedhenry.net:8080/job/fh-template-apps_pullrequests/333/

**Comment by bleathem** [comment]
Thanks @jasonmadigan!

I created the PR for fhcap a while back (I used the PR commit to create my cluster):
https://github.com/fheng/fhcap/pull/1726

**Pull request merged**
