### PR TITLE
Bumping Version

### PR DESCRIPTION
**Pull request by secondsun**
This is bumping bob

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by matzew** [comment]
@edewit @secondsun should this go to 3.12 branch ? in order to make it into the RC2 for 3.12? or is master just good enough

A bit overasked here, if needed or not

**Comment by secondsun** [comment]
@matzew There is also a PR for this to 3.12 as well.  IIRC 3.12 doesn't get merged back into master.

HOwever, @odra merged a PR that is later than this one but includes the changes made by this PR.

**Comment by matzew** [comment]
> @matzew There is also a PR for this to 3.12 as well. IIRC 3.12 doesn't get merged back into master.

ah, ok - was not sure about a 3.12 PR - yes, it' correct, because 3.12 is it's own branch

> HOwever, @odra merged a PR that is later than this one but includes the changes made by this PR.

I am not sure if that should really all matter, if one PR was send before or not. I think the manual version bumps here are part of the problem

**Comment by secondsun** [comment]
@matzew My PR has the build #411 from bob.  His PR has build #414 (I think).  So there are three builds of this project unaccounted for in this PR which may or may not be obsoleted by one of the newer builds.

**Comment by secondsun** [comment]
This PR has been incorportated into other PRs

**Pull request closed without merging**
