### PR TITLE
removed screenshots

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by nialldonnellyfh** [comment]
@edewit Seems to be failing looking for the project screenshot.

**Comment by fheng-build-servers** [comment]
@jasonmadigan please review this PR.

**Comment by nialldonnellyfh** [comment]
Not sure the screenshots should be removed. Moved to the template config instead?

**Comment by edewit** [comment]
@nialldonnellyfh it's an empty screen so...

**Comment by corinnekrych** [comment]
closing stale  PR

**Pull request closed without merging**
