### PR TITLE
bug fix RHMAP-9695

### PR DESCRIPTION
**Pull request by edewit**
bump version @mmurphy

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by edewit** [comment]
fhcap https://github.com/fheng/fhcap/pull/3061

**Comment by mmurphy** [comment]
Does this build artefact include your updates?
global.json doesn't refer to: https://github.com/feedhenry-templates/blank-cordova-app
Is that ok?

**Comment by mmurphy** [comment]
looks like the repos have been moved and the global.json points to the old location, which then re-directs to the new.

**Comment by mmurphy** [comment]
also fhcap https://github.com/fheng/fhcap/pull/3069

**Pull request merged**
