### PR TITLE
Bump version of project

### PR DESCRIPTION
**Pull request by wtrocki**
@wei-lee  @pb82  @mmurphy - Can you quickly check that one?

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* There should be an associated fhcap PR with this change - please provide a link to this
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by wtrocki** [comment]
I'm not sure why so many  changes there. I will update branches manually and then push it again.

**Comment by wtrocki** [comment]
Retest this please

**Comment by wtrocki** [comment]
Build is failing but branch and PR exist. https://github.com/feedhenry-templates/sync-cloud/pull/27
I executed everything as in guide: https://github.com/fheng/fh/wiki/Updating-App-Templates

**Comment by wtrocki** [comment]
@jasonmadigan Have you seen this error before?

**Comment by jasonmadigan** [comment]
@wtrocki I'd keep master global.json pointing to master HEAD for all templates (this is fine to get a build just for testing, though)

Build failing because `sync_app` branch doesn't exist on sync_app origin repo

**Comment by wtrocki** [comment]
Retest this please

**Comment by mmurphy** [comment]
@wtrocki is there an fhcap update for this?

**Pull request merged**
