### PR TITLE
Remove HelloWord and call it starter, like done on the repos

### PR DESCRIPTION
**Pull request by matzew**
To avoid confusion... the "Push Hello World" should be called Starter...

### CODE REVIEW

**Comment by matzew** [comment]
@edewit @corinnekrych mind to review/merge ?

**Comment by danielpassos** [comment]
@matzew You need to bump the templates version in `package.json`

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by matzew** [comment]
@danielpassos done!

**Comment by corinnekrych** [comment]
@matzew I'm +1 with the rename. You need to JIRA though.

**Comment by matzew** [comment]
@corinnekrych ok... bureaucracy at work :smile: 

I think it's bad if trivial fixes like this really need a JIRA, but here we go:
https://issues.jboss.org/browse/FH-2490

:tada:

**Pull request merged**
