### PR TITLE
removing outdated ORCL crm template from config

### PR DESCRIPTION
**Pull request by matzew**
Done for RHMAP-6137

### CODE REVIEW

**Comment by matzew** [comment]
For what ever weird reasons.... this PR hangs... like https://github.com/feedhenry/fh-template-apps/pull/184 did too 😢

**Comment by jasonmadigan** [comment]
retest this please

**Comment by jasonmadigan** [comment]
@matzew should be back in business. A bunch of webhooks expired last week, thought I got them all except this one.

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by david-martin** [comment]
@matzew Might be good to deploy the related fhcap branch to bring in the update templates artifact, then refresh them in the studio and verify the oracle service is no longer there

**Comment by matzew** [comment]
@david-martin So, manually provisioning of "44eaaad8617eb2996ce3b30b267ae7fac8739afd" from the referenced Bumping components for RHMAP-6137_orclcrm_remove #2372 PR gives me an env. that has no supercore running :-( 

```
FeedHenry-SuperCore is not running  ERROR
```

**Comment by matzew** [comment]
I see this on two different clusters (one I now deleted), but `testing.matzew-bf.skunkhenry.com` still shows that.

Note, yesterday I could provision it just fine w/ a different commit.

However I do not think that error is directly related to my "fix" or PR here

**Comment by matzew** [comment]
@david-martin so, in http://testing.matzew-bf.skunkhenry.com/#services/new I no longer see the 'CRM' template

**Comment by david-martin** [comment]
@matzew Looks good, Merging

**Comment by matzew** [comment]
@david-martin I think once 4.1 / 3.12 are really released, it's perhaps good to remove the template? or should be just keep it for a bit, shouldnt cause harm, since it's now removed from the central config

**Pull request merged**
