### PR TITLE
Adding SAML templates

### PR DESCRIPTION
**Pull request by jasonmadigan**

### CODE REVIEW

**Comment by fheng-build-servers** [comment]
SonarQube analysis reported 1 issue:
* MINOR 1 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Add an empty new line at the end of this file.](https://github.com/feedhenry/fh-template-apps/blob/11c309e981f502bb7fd39587ac614c603e33a6e1/package.json) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=json%3Aempty-line-end-of-file)

**Comment by fheng-build-servers** [comment]
SonarQube analysis reported 2 issues:
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Add an empty new line at the end of this file.](https://github.com/feedhenry/fh-template-apps/blob/c0181f32272dc33bf87333cf7323f5dc8b9d00ec/global.json) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=json%3Aempty-line-end-of-file)
* MINOR [Add an empty new line at the end of this file.](https://github.com/feedhenry/fh-template-apps/blob/c0181f32272dc33bf87333cf7323f5dc8b9d00ec/package.json) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=json%3Aempty-line-end-of-file)

**Comment by jasonmadigan** [comment]
retest this please

**Comment by fheng-build-servers** [comment]
SonarQube analysis reported 2 issues:
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Add an empty new line at the end of this file.](https://github.com/feedhenry/fh-template-apps/blob/c0181f32272dc33bf87333cf7323f5dc8b9d00ec/global.json) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=json%3Aempty-line-end-of-file)
* MINOR [Add an empty new line at the end of this file.](https://github.com/feedhenry/fh-template-apps/blob/c0181f32272dc33bf87333cf7323f5dc8b9d00ec/package.json) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=json%3Aempty-line-end-of-file)

**Pull request merged**
