### PR TITLE
Updating version to 3.18.0

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
Just incrementing the minor version to be able to get a new build of
this project and be able to update the fhcap component.

Modifications:
Update the version in package.json and sonar-project.properties.

Result:
The built dist/fh-template-apps-3.18.0.tar.gz will include the latest
for appforms-project-client

JIRA:
https://issues.jboss.org/browse/RHMAP-4762

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* There should be an associated fhcap PR with this change - please provide a link to this
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

In order to update fhcap with your component change please execute:
`fhcap component update fh-template-apps 3.18.0 354`

**Comment by danbev** [comment]
"retest this please"

**Comment by danbev** [comment]
This is the [fhcap pr](https://github.com/fheng/fhcap/pull/1945) for this work.

**Comment by danbev** [comment]
@nialldonnellyfh I'd like to merge this and I know you've already verified it but could you just comment here so that it does not look like I'm merging this without a review?

**Comment by nialldonnellyfh** [comment]
@danbev Reviewed and verified on your cluster.

**Comment by nialldonnellyfh** [comment]
@danbev I'll merge this back as I need to rebase for my changes.

**Comment by danbev** [comment]
@nialldonnellyfh great, thanks for that!

**Pull request merged**
