### PR TITLE
new v4.0 branch for 3.6.1 master merge

### PR DESCRIPTION
**Pull request by grahamhillis**

### CODE REVIEW

**Comment by david-martin** [comment]
diff suppressed due to reformatting.
Only repoBranch updated to refs/head/v4.0

**Comment by grahamhillis** [comment]
Does that mean theres an issue or it's ok to use?

**Comment by david-martin** [comment]
@grahamhillis ok to use. Verified locally that the use of `fh templates update` did a massive reformat of global.json.

**Comment by david-martin** [comment]
verified in http://testing.dmtestcluster16.skunkhenry.com/

**Pull request merged**
