### PR TITLE
added xamarin apps

### PR DESCRIPTION
**Pull request by edewit**
Add the new xamarin demos to the studio

See: [FH-2627](https://issues.jboss.org/browse/FH-2627)

Added in https://github.com/fheng/fhcap/pull/1713

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by danielpassos** [comment]
@edewit You need to bump the template-apps version in [package.json](https://github.com/feedhenry/fh-template-apps/blob/master/package.json#L3), it will be used in FHCAP

PS: Rebase first to see if someone did not already to prevent use an outdated version ;)

**Comment by danielpassos** [comment]
@edewit Sorry, just realize this is in a branch here not in your own repo. I can do that for you ;)

**Comment by danielpassos** [comment]
Landed at https://github.com/feedhenry/fh-template-apps/commit/87dc07ddbf485e01d65d97ae42e15f7af54dbdfc

**Comment by danielpassos** [comment]
Tested on http://testing.passos.skunkhenry.com/

**Pull request closed without merging**
