### PR TITLE
Add Swift apps

### PR DESCRIPTION
**Pull request by danielpassos**
See: 
* [RHMAP-4835](https://issues.jboss.org/browse/RHMAP-4835)
* [RHMAP-4836](https://issues.jboss.org/browse/RHMAP-4836)

Added in https://github.com/fheng/fhcap/pull/1638

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by danielpassos** [comment]
Added in https://github.com/fheng/fhcap/pull/1638

**Comment by danielpassos** [comment]
Test using http://testing.passos.skunkhenry.com

native-ios-blank

native-ios-helloworld

**Comment by danielpassos** [comment]
@corinnekrych Could you review/merge that?

**Comment by corinnekrych** [comment]
Perfect. 
Merged 143a092f284b883ff813e861c0cd35379a4c8520

**Pull request closed without merging**
