### PR TITLE
Add welcome and blank Android templates

### PR DESCRIPTION
**Pull request by danielpassos**
See: [RHMAP-4778](https://issues.jboss.org/browse/RHMAP-4778) and [RHMAP-4779](https://issues.jboss.org/browse/RHMAP-4779)

### CODE REVIEW

**Comment by danielpassos** [comment]
@jasonmadigan Could you review that for 3.9.0?

**Comment by jasonmadigan** [comment]
@danielpassos this looks okay to me. Has this been tested somewhere?

**Comment by danielpassos** [comment]
@jasonmadigan Yes, I did that in my own instance (`passos`) but I destroyed that yesterday playing with fhcap-cli. I can ship that to a new one or in `clientsdk` if you want

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by danielpassos** [comment]
Added in fhcap in https://github.com/fheng/fhcap/pull/1611

**Comment by danielpassos** [comment]
Tested using http://testing.passos.skunkhenry.com/#projects/eflqqxcy46bd45mc3bl2v45z/apps/eflqqxboslhttj5gwlqcst6k/build

fh-templates-update

**Pull request merged**
