### PR TITLE
Changing from master to head several templates

### PR DESCRIPTION
**Pull request by secondsun**
Changing the templates which use master to use a release branch

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by matskiv** [comment]
LGTM but I will check if we have to include other templates

**Comment by matskiv** [comment]
welcome-app
helloworld-app
saml-cordova-app (but release branches/tags aren't there since 3.7)

**Comment by mmurphy** [comment]
The master branch should not refer to release branches.  global.json on master should only refer to master branches.
The release process will be changed to update the globals.json, to refer to the newly created release branches

**Comment by secondsun** [comment]
@mmurphy Thanks for the clarification!  Closing.,

**Pull request closed without merging**
