### PR TITLE
RHMAP-3967 - fh-mbaas-api@5.7.12

### PR DESCRIPTION
**Pull request by jasonmadigan**

### CODE REVIEW

**Comment by david-martin** [comment]
Reviewed.
Lets close these other 2 PRs that do the same thing with repo locations
https://github.com/feedhenry/fh-template-apps/pull/83
https://github.com/feedhenry/fh-template-apps/pull/81

**Comment by jasonmadigan** [comment]
@david-martin done.

**Comment by jasonmadigan** [comment]
Tested on http://testing.jmadigan.skunkhenry.com/#projects/zov7f6nkrjtaf2v56bs6md3o/apps/zov7f6mz2pmgolhcn7d54hu4/editor

**Comment by jasonmadigan** [comment]
Mergin'

**Comment by jasonmadigan** [comment]
https://github.com/fheng/fhcap/pull/1439

**Pull request merged**
