### PR TITLE
Add SAML apps

### PR DESCRIPTION
**Pull request by danielpassos**
* [RHMAP-2631](https://issues.jboss.org/browse/RHMAP-2631) - Add SAML Android template app in studio
* [RHMAP-2632](https://issues.jboss.org/browse/RHMAP-2632) - Add SAML iOS template app in studio
* [RHMAP-2633](https://issues.jboss.org/browse/RHMAP-2633) - Add SAML Windows template app in studio

### CODE REVIEW

**Comment by danielpassos** [comment]
@jasonmadigan Could you give it a spin?

**Comment by jasonmadigan** [comment]
@danielpassos happy to give this a quick test for 3.7.0 - could you rebase from the latest master? We can get an fhcap PR together with this then too.

**Comment by danielpassos** [comment]
@jasonmadigan Seems someone else already added it on master => https://github.com/feedhenry/fh-template-apps/blob/master/global.json#L15-L83

**Comment by jasonmadigan** [comment]
@danielpassos cool, we can probably close this so!

**Comment by jasonmadigan** [comment]
https://github.com/feedhenry/fh-template-apps/pull/104

**Pull request closed without merging**
