### PR TITLE
Adding fix for  RHMAP-2632

### PR DESCRIPTION
**Pull request by jasonmadigan**

### CODE REVIEW

**Comment by jasonmadigan** [comment]
retest this please

**Comment by grdryn** [comment]
:+1: 1:

**Comment by jasonmadigan** [comment]
retest this please

**Comment by jasonmadigan** [comment]
@lgriffin unsure what's up with the SonarQube job here: http://bob.feedhenry.net:8080/job/fh-template-apps_sonar-pullrequests/27/console

**Comment by jasonmadigan** [comment]
retest this please

**Comment by lgriffin** [comment]
retest this please

**Pull request merged**
