### PR TITLE
bump version to get xamarin blank

### PR DESCRIPTION
**Pull request by corinnekrych**
[deploy][clientsdk]

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* There should be an associated fhcap PR with this change - please provide a link to this
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

In order to update fhcap with your component change please execute:
`fhcap component update fh-template-apps 3.25.0 368`

**Comment by jasonmadigan** [comment]
[deploy][clientsdk]

**Comment by jasonmadigan** [comment]
See: http://bob.feedhenry.net:8080/view/cluster-deploy/job/cluster-deploy-multi/179/

**Comment by jasonmadigan** [comment]
@corinnekrych I see that the clientsdk cluster is using a "local" chef server, so this won't work with the new deploy commands right now (see known issues from that mail). If you want to take advantage of it right now, I'd delete the cluster and re-create it using bob as a chef-server.

**Comment by corinnekrych** [comment]
@jasonmadigan ahhh thanks for the tips, I'll do that

**Pull request closed without merging**
