### PR TITLE
fix apple icon

### PR DESCRIPTION
**Pull request by corinnekrych**
@secondsun here it is on the FH-v3.8.0 branch

### CODE REVIEW

**Comment by secondsun** [comment]
LGTM

**Comment by mmurphy** [comment]
is this going into 3.8.0?
Is there an fhcap PR for this?

**Comment by mmurphy** [comment]
@corinnekrych @secondsun was there an fhcap PR for this?

**Comment by mmurphy** [comment]
I've included it in: https://github.com/fheng/fhcap/commit/bd39f0e65f8772c66568462394a42f77df7c5f58

**Comment by corinnekrych** [comment]
@mmurphy thanks!

**Pull request merged**
