### PR TITLE
add saml xamarin

### PR DESCRIPTION
**Pull request by edewit**
fixing issue [FH-2698](https://issues.jboss.org/browse/FH-2698)

@secondsun added the last demo

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by secondsun** [comment]
+1 Loaded it up and tested

**Comment by secondsun** [comment]
landed @https://github.com/feedhenry/fh-template-apps/commit/bc32c13c4e5a10296f13c1ff2647cda291939579

**Comment by matzew** [comment]
@edewit @secondsun   should this go to 3.12 branch ?   in order to make it into the RC2 for 3.12? or is master just good enough

**Comment by matzew** [comment]
A bit overasked here, if needed or not....

**Comment by matzew** [comment]
Looking at: https://github.com/feedhenry/fh-template-apps/blob/FH-v3.12.0/global.json


I don't see this link: git://github.com/feedhenry-templates/saml-xamarin-app.gi

**Pull request closed without merging**
